language: node_js
node_js:
  - "12.13"

deploy:
  on:
    branch: master
  provider: npm
  email: chris.a.small+npm@gmail.com
  api_key:
    secure: R/ZN0SwgPdhtD+qzI/4mCJBN8L5OgZOIm3zqtiZyyp98oVKIrB2DdiZQS2qMUbn5pIgqEsFrxmu8Dg50CLZEMEOZjtdBqD9d22JFGIHzhWgFPHAfATKh3qc/+eQSroWJhECuKcajEYtWEE42UVJyZzkW9mCEhb1XUmTPzx9ecUyJ5j8rUbAt9NBZ3CBErrpmIoO2PV9bz9PlsgrdSnMzVmOXR3E1vOnHxUck0TpCT191T5dbSxq0Cpx1apdONoLSHcJ55sgPnXuEY8YMsM+TdnPO93iXAtAldc7HcvbdJP6eXf+3uk15W68xauMfv7SiZEG9o+SMHyo7PxRLqqeQaWK9oF6VTLh+MHG2FZ32rdnA/WSBiPvJxGnaTEcZnbXFFwknUlrGp5wIJyEuBmyBmtLJ8p3Y9tV2fTqFY+aU41mWItQWWn5MPKt8CY7Jlh7nJRCruK4yBYf6vq8P0CaCr6smJsua835JyxPL4+JF+UgmwYoOhDRjR5HweQqvQ7dF5fODAQxllKQ3AfaKofkbPybBTlIqQSGQGOkiSN7ACJt/ni3RYS+fn4SsVSP3o0mBT2xNTRm41YO/wRqtzHrIpM5wvcsriNQzyn5pUtd7OnrGiAGoPX5eh3N4ytJG9JJA3CqNL/bsXEIgokOm3OlANU7nRHgahJRcQz72DvYL6Sc=
