/**
 * Roadkill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthorizationResponse model module.
 * @module model/AuthorizationResponse
 * @version 3.0
 */
class AuthorizationResponse {
    /**
     * Constructs a new <code>AuthorizationResponse</code>.
     * @alias module:model/AuthorizationResponse
     */
    constructor() { 
        
        AuthorizationResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthorizationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthorizationResponse} obj Optional instance to populate.
     * @return {module:model/AuthorizationResponse} The populated <code>AuthorizationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorizationResponse();

            if (data.hasOwnProperty('jwtToken')) {
                obj['jwtToken'] = ApiClient.convertToType(data['jwtToken'], 'String');
            }
            if (data.hasOwnProperty('refreshToken')) {
                obj['refreshToken'] = ApiClient.convertToType(data['refreshToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} jwtToken
 */
AuthorizationResponse.prototype['jwtToken'] = undefined;

/**
 * @member {String} refreshToken
 */
AuthorizationResponse.prototype['refreshToken'] = undefined;






export default AuthorizationResponse;

