/**
 * Roadkill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PageRequest model module.
 * @module model/PageRequest
 * @version 3.0
 */
class PageRequest {
    /**
     * Constructs a new <code>PageRequest</code>.
     * Represents page information in Roadkill.
     * @alias module:model/PageRequest
     * @param title {String} The title of the page.
     * @param createdBy {String} The user who created the page.
     * @param isLocked {Boolean} Whether the page is locked so no edits can be made (except by admins).
     * @param tags {String} The list of tags, comma separated, for the page.
     */
    constructor(title, createdBy, isLocked, tags) { 
        
        PageRequest.initialize(this, title, createdBy, isLocked, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, createdBy, isLocked, tags) { 
        obj['title'] = title;
        obj['createdBy'] = createdBy;
        obj['isLocked'] = isLocked;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>PageRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageRequest} obj Optional instance to populate.
     * @return {module:model/PageRequest} The populated <code>PageRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageRequest();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('seoFriendlyTitle')) {
                obj['seoFriendlyTitle'] = ApiClient.convertToType(data['seoFriendlyTitle'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('lastModifiedBy')) {
                obj['lastModifiedBy'] = ApiClient.convertToType(data['lastModifiedBy'], 'String');
            }
            if (data.hasOwnProperty('lastModifiedOn')) {
                obj['lastModifiedOn'] = ApiClient.convertToType(data['lastModifiedOn'], 'Date');
            }
            if (data.hasOwnProperty('isLocked')) {
                obj['isLocked'] = ApiClient.convertToType(data['isLocked'], 'Boolean');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The unique Id of the page. This is generated on the server.
 * @member {Number} id
 */
PageRequest.prototype['id'] = undefined;

/**
 * The title of the page.
 * @member {String} title
 */
PageRequest.prototype['title'] = undefined;

/**
 * The url-friendly slug for the page title.
 * @member {String} seoFriendlyTitle
 */
PageRequest.prototype['seoFriendlyTitle'] = undefined;

/**
 * The user who created the page.
 * @member {String} createdBy
 */
PageRequest.prototype['createdBy'] = undefined;

/**
 * The UTC-based date the page was created.
 * @member {Date} createdOn
 */
PageRequest.prototype['createdOn'] = undefined;

/**
 * The user who last modified the page. If the page has note been modified yet, this will match the CreatedBy property.
 * @member {String} lastModifiedBy
 */
PageRequest.prototype['lastModifiedBy'] = undefined;

/**
 * The date the page was last modified on. If the page has note been modified yet, this will match the creation date.
 * @member {Date} lastModifiedOn
 */
PageRequest.prototype['lastModifiedOn'] = undefined;

/**
 * Whether the page is locked so no edits can be made (except by admins).
 * @member {Boolean} isLocked
 */
PageRequest.prototype['isLocked'] = undefined;

/**
 * The list of tags, comma separated, for the page.
 * @member {String} tags
 */
PageRequest.prototype['tags'] = undefined;






export default PageRequest;

