/**
 * Roadkill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PageVersionResponse model module.
 * @module model/PageVersionResponse
 * @version 3.0
 */
class PageVersionResponse {
    /**
     * Constructs a new <code>PageVersionResponse</code>.
     * @alias module:model/PageVersionResponse
     */
    constructor() { 
        
        PageVersionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageVersionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageVersionResponse} obj Optional instance to populate.
     * @return {module:model/PageVersionResponse} The populated <code>PageVersionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageVersionResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('pageId')) {
                obj['pageId'] = ApiClient.convertToType(data['pageId'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('author')) {
                obj['author'] = ApiClient.convertToType(data['author'], 'String');
            }
            if (data.hasOwnProperty('dateTime')) {
                obj['dateTime'] = ApiClient.convertToType(data['dateTime'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PageVersionResponse.prototype['id'] = undefined;

/**
 * @member {Number} pageId
 */
PageVersionResponse.prototype['pageId'] = undefined;

/**
 * @member {String} text
 */
PageVersionResponse.prototype['text'] = undefined;

/**
 * @member {String} author
 */
PageVersionResponse.prototype['author'] = undefined;

/**
 * @member {Date} dateTime
 */
PageVersionResponse.prototype['dateTime'] = undefined;






export default PageVersionResponse;

