/**
 * Roadkill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PageResponse model module.
 * @module model/PageResponse
 * @version 3.0
 */
class PageResponse {
    /**
     * Constructs a new <code>PageResponse</code>.
     * Represents page information in Roadkill.
     * @alias module:model/PageResponse
     * @param title {String} The title of the page.
     * @param createdBy {String} The user who created the page.
     * @param isLocked {Boolean} Whether the page is locked so no edits can be made (except by admins).
     * @param tagsAsCsv {String} The list of tags, comma seperated, for the page.
     */
    constructor(title, createdBy, isLocked, tagsAsCsv) { 
        
        PageResponse.initialize(this, title, createdBy, isLocked, tagsAsCsv);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, createdBy, isLocked, tagsAsCsv) { 
        obj['title'] = title;
        obj['createdBy'] = createdBy;
        obj['isLocked'] = isLocked;
        obj['tagsAsCsv'] = tagsAsCsv;
    }

    /**
     * Constructs a <code>PageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageResponse} obj Optional instance to populate.
     * @return {module:model/PageResponse} The populated <code>PageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('seoFriendlyTitle')) {
                obj['seoFriendlyTitle'] = ApiClient.convertToType(data['seoFriendlyTitle'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('lastModifiedBy')) {
                obj['lastModifiedBy'] = ApiClient.convertToType(data['lastModifiedBy'], 'String');
            }
            if (data.hasOwnProperty('lastModifiedOn')) {
                obj['lastModifiedOn'] = ApiClient.convertToType(data['lastModifiedOn'], 'Date');
            }
            if (data.hasOwnProperty('isLocked')) {
                obj['isLocked'] = ApiClient.convertToType(data['isLocked'], 'Boolean');
            }
            if (data.hasOwnProperty('tagsAsCsv')) {
                obj['tagsAsCsv'] = ApiClient.convertToType(data['tagsAsCsv'], 'String');
            }
            if (data.hasOwnProperty('tagList')) {
                obj['tagList'] = ApiClient.convertToType(data['tagList'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The unique Id of the page. This is generated on the server.
 * @member {Number} id
 */
PageResponse.prototype['id'] = undefined;

/**
 * The title of the page.
 * @member {String} title
 */
PageResponse.prototype['title'] = undefined;

/**
 * The url-friendly slug for the page title.
 * @member {String} seoFriendlyTitle
 */
PageResponse.prototype['seoFriendlyTitle'] = undefined;

/**
 * The user who created the page.
 * @member {String} createdBy
 */
PageResponse.prototype['createdBy'] = undefined;

/**
 * The UTC-based date the page was created.
 * @member {Date} createdOn
 */
PageResponse.prototype['createdOn'] = undefined;

/**
 * The user who last modified the page. If the page has note been modified yet, this will match the CreatedBy property.
 * @member {String} lastModifiedBy
 */
PageResponse.prototype['lastModifiedBy'] = undefined;

/**
 * The date the page was last modified on. If the page has note been modified yet, this will match the creation date.
 * @member {Date} lastModifiedOn
 */
PageResponse.prototype['lastModifiedOn'] = undefined;

/**
 * Whether the page is locked so no edits can be made (except by admins).
 * @member {Boolean} isLocked
 */
PageResponse.prototype['isLocked'] = undefined;

/**
 * The list of tags, comma seperated, for the page.
 * @member {String} tagsAsCsv
 */
PageResponse.prototype['tagsAsCsv'] = undefined;

/**
 * The tags for the page as an array.
 * @member {Array.<String>} tagList
 */
PageResponse.prototype['tagList'] = undefined;






export default PageResponse;

