/**
 * Roadkill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RoadkillApi);
  }
}(this, function(expect, RoadkillApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RoadkillApi.PageResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PageResponse', function() {
    it('should create an instance of PageResponse', function() {
      // uncomment below and update the code to test PageResponse
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be.a(RoadkillApi.PageResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property seoFriendlyTitle (base name: "seoFriendlyTitle")', function() {
      // uncomment below and update the code to test the property seoFriendlyTitle
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property lastModifiedBy (base name: "lastModifiedBy")', function() {
      // uncomment below and update the code to test the property lastModifiedBy
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property lastModifiedOn (base name: "lastModifiedOn")', function() {
      // uncomment below and update the code to test the property lastModifiedOn
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property isLocked (base name: "isLocked")', function() {
      // uncomment below and update the code to test the property isLocked
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property tagsAsCsv (base name: "tagsAsCsv")', function() {
      // uncomment below and update the code to test the property tagsAsCsv
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

    it('should have the property tagList (base name: "tagList")', function() {
      // uncomment below and update the code to test the property tagList
      //var instane = new RoadkillApi.PageResponse();
      //expect(instance).to.be();
    });

  });

}));
