/**
 * Roadkill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RoadkillApi);
  }
}(this, function(expect, RoadkillApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RoadkillApi.PageVersionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PageVersionsApi', function() {
    describe('pageVersionsAdd', function() {
      it('should call pageVersionsAdd successfully', function(done) {
        //uncomment below and update the code to test pageVersionsAdd
        //instance.pageVersionsAdd(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pageVersionsAllVersions', function() {
      it('should call pageVersionsAllVersions successfully', function(done) {
        //uncomment below and update the code to test pageVersionsAllVersions
        //instance.pageVersionsAllVersions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pageVersionsDelete', function() {
      it('should call pageVersionsDelete successfully', function(done) {
        //uncomment below and update the code to test pageVersionsDelete
        //instance.pageVersionsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pageVersionsFindPageVersionsByAuthor', function() {
      it('should call pageVersionsFindPageVersionsByAuthor successfully', function(done) {
        //uncomment below and update the code to test pageVersionsFindPageVersionsByAuthor
        //instance.pageVersionsFindPageVersionsByAuthor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pageVersionsFindPageVersionsByPageId', function() {
      it('should call pageVersionsFindPageVersionsByPageId successfully', function(done) {
        //uncomment below and update the code to test pageVersionsFindPageVersionsByPageId
        //instance.pageVersionsFindPageVersionsByPageId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pageVersionsGet', function() {
      it('should call pageVersionsGet successfully', function(done) {
        //uncomment below and update the code to test pageVersionsGet
        //instance.pageVersionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pageVersionsGetLatestVersion', function() {
      it('should call pageVersionsGetLatestVersion successfully', function(done) {
        //uncomment below and update the code to test pageVersionsGetLatestVersion
        //instance.pageVersionsGetLatestVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pageVersionsUpdate', function() {
      it('should call pageVersionsUpdate successfully', function(done) {
        //uncomment below and update the code to test pageVersionsUpdate
        //instance.pageVersionsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
